### ISSUE TITLE
Documentation site build error

### ISSUE THREAD

**Issue by ZviBaratz** [nipy/nibabel#1201]
The execution of [`build_modref_templates.py`](https://github.com/nipy/nibabel/blob/master/doc/tools/build_modref_templates.py) in [`doc/Makefile`](https://github.com/nipy/nibabel/blob/cbd7690143d9c203e1a8ebdf67bb5832f719db06/doc/Makefile#L46) raises multiple `AttributeError`s from `nibabel._version`.

**Comment by effigies** [comment]
You need to run `hatch build --hooks-only` to populate that file.

**Comment by ZviBaratz** [comment]
@effigies Which file? Also, I am still getting the same exceptions.

**Comment by effigies** [comment]
Hmm. Maybe try `pip install -e .`. If you have a non-editable install, then you might be getting a version mismatch.

**Comment by effigies** [comment]
And what's your command? I always just do `make -C doc html` and that works for me if I've previously run `pip install -e ".[doc]"`.

**Comment by ZviBaratz** [comment]
I am running an editable install, and I was using `make html` from within `doc/`. Tried both re-running the editable installation, and using `make -C doc html` from the package root, but I am still getting the same messages 😕

**Comment by effigies** [comment]
Want to share the errors?

**Comment by ZviBaratz** [comment]
Of course:
```
make: Entering directory '/home/zvi/Projects/nibabel/doc'
mkdir -p ../build/html ../build/doctrees
sphinx-build -b html -d ../build/doctrees   source ../build/html
Running Sphinx v5.3.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] reference/nibabel._version                                                                                                                                          
/home/zvi/Projects/nibabel/doc/source/reference/nibabel._version.rst:8: WARNING: autosummary: failed to import NotThisMethod.
Possible hints:
* ModuleNotFoundError: No module named 'nibabel._version.NotThisMethod'; 'nibabel._version' is not a package
* AttributeError: module 'nibabel._version' has no attribute 'NotThisMethod'
* ValueError: not enough values to unpack (expected 2, got 1)
* ModuleNotFoundError: No module named 'NotThisMethod'
* KeyError: 'NotThisMethod'
/home/zvi/Projects/nibabel/doc/source/reference/nibabel._version.rst:8: WARNING: autosummary: failed to import VersioneerConfig.
Possible hints:
* AttributeError: module 'nibabel._version' has no attribute 'VersioneerConfig'
* ModuleNotFoundError: No module named 'VersioneerConfig'
* ValueError: not enough values to unpack (expected 2, got 1)
* ModuleNotFoundError: No module named 'nibabel._version.VersioneerConfig'; 'nibabel._version' is not a package
* KeyError: 'VersioneerConfig'
/home/zvi/Projects/nibabel/doc/source/reference/nibabel._version.rst:8: WARNING: autosummary: failed to import get_config.
Possible hints:
* AttributeError: module 'nibabel._version' has no attribute 'get_config'
* KeyError: 'get_config'
* ModuleNotFoundError: No module named 'get_config'
* ValueError: not enough values to unpack (expected 2, got 1)
* ModuleNotFoundError: No module named 'nibabel._version.get_config'; 'nibabel._version' is not a package
/home/zvi/Projects/nibabel/doc/source/reference/nibabel._version.rst:8: WARNING: autosummary: failed to import get_keywords.
Possible hints:
* ModuleNotFoundError: No module named 'nibabel._version.get_keywords'; 'nibabel._version' is not a package
* KeyError: 'get_keywords'
* AttributeError: module 'nibabel._version' has no attribute 'get_keywords'
* ValueError: not enough values to unpack (expected 2, got 1)
* ModuleNotFoundError: No module named 'get_keywords'
/home/zvi/Projects/nibabel/doc/source/reference/nibabel._version.rst:8: WARNING: autosummary: failed to import get_versions.
Possible hints:
* ModuleNotFoundError: No module named 'nibabel._version.get_versions'; 'nibabel._version' is not a package
* ValueError: not enough values to unpack (expected 2, got 1)
* AttributeError: module 'nibabel._version' has no attribute 'get_versions'
* KeyError: 'get_versions'
* ModuleNotFoundError: No module named 'get_versions'
/home/zvi/Projects/nibabel/doc/source/reference/nibabel._version.rst:8: WARNING: autosummary: failed to import git_get_keywords.
Possible hints:
* ModuleNotFoundError: No module named 'nibabel._version.git_get_keywords'; 'nibabel._version' is not a package
* ModuleNotFoundError: No module named 'git_get_keywords'
* AttributeError: module 'nibabel._version' has no attribute 'git_get_keywords'
* KeyError: 'git_get_keywords'
* ValueError: not enough values to unpack (expected 2, got 1)
.........
WARNING: autodoc: failed to import function 'versions_from_parentdir' from module 'nibabel._version'; the following exception was raised:
Traceback (most recent call last):
  File "/home/zvi/Projects/nibabel/venv/lib/python3.9/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'nibabel._version' has no attribute 'versions_from_parentdir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zvi/Projects/nibabel/venv/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/zvi/Projects/nibabel/venv/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/zvi/Projects/nibabel/venv/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/zvi/Projects/nibabel/venv/lib/python3.9/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: versions_from_parentdir

looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/zvi/Projects/nibabel/doc/source/notebooks/index.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] reference/nibabel._version                                                                                                                                           
generating indices... genindex py-modindex done
writing additional pages... search done
copying downloadable files... [100%] notebooks/cross_product_error.ipynb                                                                                                                      
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 45 warnings.
```

**Comment by effigies** [comment]
I think you might have a polluted directory, as I'm seeing versioneer stuff in there. Try `make -C doc clean html`.

**Comment by ZviBaratz** [comment]
That fixed it. Thank you!
