### ISSUE TITLE
Tests: failure of `nisext.tests.test_doctest_markup.test_byter` with Python 3.5

### ISSUE THREAD

**Issue by FRidh** [nipy/nibabel#366]
The test `nisext.tests.test_doctest_markup.test_byter` fails with nibabel 2.0.1. Only fails with Python 3.5 only.

http://hydra.nixos.org/build/27003289/nixlog/1/raw

**Comment by bcipolli** [comment]
@FRidh could you check if this is solved by https://github.com/nipy/nibabel/pull/363 ?

**Comment by FRidh** [comment]
Unfortunately not.

```py
======================================================================
ERROR: nisext.tests.test_doctest_markup.test_byter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/iqq89s0zzgg8sn7s6nfnsw211rnf86yf-python3.5-nose-1.3.4/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/nix/store/r6nfwyyi4sn6vmq7zzja6sfhcga9n8g4-python3.5-numpy-1.10.1/lib/python3.5/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/home/freddy/Code/nibabel/nisext/tests/test_doctest_markup.py", line 161, in test_byter
    byter(line),
  File "/home/freddy/Code/nibabel/nisext/py3builder.py", line 238, in byter
    return codegen.to_source(tree)
  File "/home/freddy/Code/nibabel/nisext/codegen.py", line 37, in to_source
    generator.visit(node)
  File "/home/freddy/Code/nibabel/nisext/ast.py", line 319, in visit
    return self.generic_visit(node)
  File "/home/freddy/Code/nibabel/nisext/ast.py", line 327, in generic_visit
    self.visit(item)
  File "/home/freddy/Code/nibabel/nisext/ast.py", line 318, in visit
    return f(node)
  File "/home/freddy/Code/nibabel/nisext/codegen.py", line 119, in visit_Assign
    self.visit(node.value)
  File "/home/freddy/Code/nibabel/nisext/ast.py", line 318, in visit
    return f(node)
  File "/home/freddy/Code/nibabel/nisext/codegen.py", line 342, in visit_Call
    if node.starargs is not None:
AttributeError: 'Call' object has no attribute 'starargs'

----------------------------------------------------------------------
Ran 7071 tests in 215.419s

FAILED (SKIP=70, errors=1)
```

**Comment by effigies** [comment]
Can you try f1bcfcb?

**Comment by effigies** [comment]
@FRidh Try 33bbe11 (or better yet, effigies/issue-366).

**Comment by FRidh** [comment]
Still fails with your branch.

On Wed, Oct 28, 2015 at 10:18 PM, Chris Markiewicz <notifications@github.com

**Comment by effigies** [comment]
That's because I put the check in the wrong function. Try now (883c771).

**Comment by matthew-brett** [comment]
I wonder whether we should just drop this stuff now - we aren't using it, it's only useful for Python 2.5.

**Comment by FRidh** [comment]
That fixed it. Thanks.

**Comment by effigies** [comment]
Travis hasn't tested for 2.5 in [2.5 years](https://github.com/nipy/nibabel/commit/ca1dfb2314b6975f93806695b6bdba7d4b9d4287#diff-354f30a63fb0907d4ad57269548329e3L4), and there's plenty of dependence on 2.6+ features, so anybody using `nibabel` with Python 2.5 is already using an old version.

+1 for dropping 2.5 support in master.

**Comment by matthew-brett** [comment]
We don't support 2.5, but I left the testing machinery in there in case anyone else was using it to support Python 2.5.  I guess probably not...

**Comment by matthew-brett** [comment]
https://github.com/nipy/nibabel/pull/369

**Comment by effigies** [comment]
Issue obviated by #369.
