### ISSUE TITLE
PARREC; B1 map double TR error

### ISSUE THREAD

**Issue by ilogue** [nipy/nibabel#399]
```
In[6]:  prov.add(parfile)
[provenance] Error inspecting file: /redshirt_array/data/phantom_qT1_slu/phantom_qT1_ ~SNIP~ _WIP_B1MAP_SENSE_24_1.PAR
Traceback (most recent call last):
Out[6]:   File "/home/mrjeffs/Software/niprov/niprov/adding.py", line 69, in add
    img.inspect()
  File "/home/mrjeffs/Software/niprov/niprov/parrec.py", line 14, in inspect
    img = self.libs.nibabel.load(self.path)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/loadsave.py", line 44, in load
    return guessed_image_type(filename).from_filename(filename, **kwargs)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/keywordonly.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/parrec.py", line 1048, in from_filename
    scaling=scaling)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/keywordonly.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/parrec.py", line 1013, in from_file_map
    permit_truncated=permit_truncated)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/parrec.py", line 632, in from_fileobj
    info, image_defs = parse_PAR_header(fileobj)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/parrec.py", line 461, in parse_PAR_header
    general_info = _process_gen_dict(gen_dict)
  File "/home/mrjeffs/Software/anaconda/lib/python2.7/site-packages/nibabel/parrec.py", line 295, in _process_gen_dict
    value = props[1](value)
ValueError: invalid literal for float(): 70.892  190.892
(<niprov.parrec.ParrecFile at 0x7f8d0a3b1650>, 'failed')
```

@Eric89GXL @mrjeffs
We have a B1 map in a PARREC file that lists two TR values in the header, as expected for this protocol, but are running into an error for it.

The field format for TR is defined here:
https://github.com/nipy/nibabel/blob/master/nibabel/parrec.py#L151

But if this became a list/tuple, I'm not sure how that would affect code downstream.

**Comment by grlee77** [comment]
@ilogue
I can probably make a small fix for this issue

Can you paste the line from the .PAR file header that is causing the problem here?  I assume the multiple TRs are just space separated?

Can you clarify if this is something that can normally occur in .PAR files resulting from Philips product sequences? (i.e. it is not due to a customized software patch)

**Comment by ilogue** [comment]
The line looks like this:

```
.    Repetition time [ms]               :   70.303  190.303  
```

So there are two spaces in between.

I am not sure if this is affected by patches on our scanner, but the behavior is as expected.

Thanks for looking into this.

**Comment by matthew-brett** [comment]
@ilogue - can we close this issue?  Would you mind doing the honors if so?

**Comment by ilogue** [comment]
Excellent work @grlee77 Many thanks!
