### ISSUE TITLE
Test failing on Python 3.7

### ISSUE THREAD

**Issue by sanjayankur31** [nipy/nibabel#650]
```
======================================================================
FAIL: nibabel.tests.test_testing.test_clear_and_catch_warnings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fedora/ankursinha/nibabel-virt/lib64/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/fedora/ankursinha/nibabel/nibabel/tests/test_testing.py", line 89, in test_clear_and_catch_warnings
    assert_warn_len_equal(my_mod, 1)
  File "/home/fedora/ankursinha/nibabel/nibabel/tests/test_testing.py", line 72, in assert_warn_len_equal
    assert_equal(len(mod_warns), 2)  # including 'version'
AssertionError: 1 != 2

----------------------------------------------------------------------
```

Tried on a fresh python 3.7 virtual env too and got the same.

**Comment by effigies** [comment]
Closed by #651.
