### ISSUE TITLE
Nibabel Working with large Nifti files causes errors in python

### ISSUE THREAD

**Issue by Nonimus** [nipy/nibabel#662]
Heyo Guys my Problem is that my Code produces the error that there is not enough memory available to process a command. (Windows Error 8) The file is a .nii with 360MB and the Code is the following

```
import nibabel as nib
import numpy as np
from nibabel.viewers import OrthoSlicer3D

img = nib.load('File.nii')
img_data = np.array(img.dataobj)

OrthoSlicer3D(img_data).show()
```
This is one of the variants.
`
img.get_data() or img.get_fdata() `
produce the same error. It works with files that have a lower size.

The data is a fmrt sequence about 28 minutes.

Is there maybe a possibility to split the data before reading the whole file or a possibility only to read a specific amount of the file.

```Traceback (most recent call last):
  File "D:/Users/Fabs-spinner/PycharmProjects/Projekt/Main.py", line 8, in <module>
    img_data = np.array(img.dataobj)
  File "D:\Users\Fabs-spinner\PycharmProjects\Projekt\venv\lib\site-packages\nibabel\arrayproxy.py", line 293, in __array__
    raw_data = self.get_unscaled()
  File "D:\Users\Fabs-spinner\PycharmProjects\Projekt\venv\lib\site-packages\nibabel\arrayproxy.py", line 288, in get_unscaled
    mmap=self._mmap)
  File "D:\Users\Fabs-spinner\PycharmProjects\Projekt\venv\lib\site-packages\nibabel\volumeutils.py", line 509, in array_from_file
    offset=offset)
  File "D:\Users\Fabs-spinner\PycharmProjects\Projekt\venv\lib\site-packages\numpy\core\memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [WinError 8] Zur Verarbeitung dieses Befehls sind nicht genügend Speicherressourcen verfügbar
```

Edit: It works with lower sices if I take just some slices. I.O. like `img_data = np.array(img.dataobj[:,:,:,1:100])`

**Comment by yarikoptic** [comment]
having a traceback from crash could help may be ;-)

**Comment by effigies** [comment]
Hi @Nonimus. Sorry for the slow response. Nibabel does work to minimize memory usage; have you tried using `img.orthoview()`? That passes `img.dataobj` directly to `OrthoSlicer3D`, and should hopefully permit nibabel's memory optimizations to work.

**Comment by Nonimus** [comment]
Heyo,
that unfortunally produces the same error.

We now just simply load single slices :) That works well for our purposes.


```
Traceback (most recent call last):
  File "F:/Users/fkpro/PycharmProjects/LinProjekt/Main.py", line 8, in <module>
    img.orthoview()
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\nibabel\spatialimages.py", line 486, in orthoview
    title=self.get_filename())
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\nibabel\viewers.py", line 73, in __init__
    data = np.asanyarray(data)
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\numpy\core\numeric.py", line 544, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\nibabel\arrayproxy.py", line 290, in __array__
    raw_data = self.get_unscaled()
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\nibabel\arrayproxy.py", line 285, in get_unscaled
    mmap=self._mmap)
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\nibabel\volumeutils.py", line 509, in array_from_file
    offset=offset)
  File "F:\Users\fkpro\PycharmProjects\LinProjekt\lib\site-packages\numpy\core\memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
OSError: [WinError 8] Zur Verarbeitung dieses Befehls sind nicht genügend Speicherressourcen verfügbar
```

**Comment by effigies** [comment]
Okay. Glad you found something that works. It's a useful tool, but not the most optimized. If you do find ways to improve its memory usage, feel free to submit a pull request.
