### ISSUE TITLE
How to load byte format of nifti file with nibabel method?

### ISSUE THREAD

**Issue by ytliang97** [nipy/nibabel#905]
system: Mac OS Catalina 10.15
language: python3.6.9
nibabel version: 3.0.0

Hi, I want to convert nifti file(nii.gz) into bytes string that I could use to generate tensorflow record. But when I tried this:

```python
import nibabel as nib
import matplotlib.pyplot as plt
import tensorflow as tf

FLAGS = tf.app.flags.FLAGS

tf.app.flags.DEFINE_string(
    'data_path', '',
    'nifti data path.')

#e.g. FLAGS.data_path = 'BraTS19_CBICA_AAB_1_t1ce.nii.gz' or 'BraTS19_CBICA_AAB_1_t1ce.nii'

def main(_):
    with open(FLAGS.data_path, 'rb') as f:
        bytes_ = f.read()
        print(type(f))
        print(type(bytes_))

        file = nib.load(bytes_)
        print(type(file))
        print(file.shape)

        data = file.get_data()
        print(type(data))
        print(data.shape)
        
        plt.imshow(data[:,:,50], cmap='Greys_r')
        plt.show()

if __name__ == '__main__':
    tf.app.run()
```
I got:
```
<class '_io.BufferedReader'>
<class 'bytes'>
Traceback (most recent call last):
  File "own-loading_nifti_file.py", line 31, in <module>
    tf.app.run()
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "own-loading_nifti_file.py", line 19, in main
    file = nib.load(bytes_)
  File "/usr/local/Cellar/python@3.6/3.6.9_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    stat_result = os.stat(filename)
ValueError: stat: embedded null character in path
```

And I have checked that there aren't any '\0' nor '\t' in my file path.

It seems `nib.load()` could only feed file path.

Is there another method in nibabel could load byte object? I have searched nibabel manual, but I couldn't find it out.

Any suggestions? Thanks!

**Comment by effigies** [comment]
For this, use `nib.Nifti1Image.from_bytes()`.

We may be able to abstract out the machinery from load to detect image type to allow a general loading function, but right now you'll need to know the type first.

**Comment by ytliang97** [comment]
Thanks for reply, I’ll try it later.

**Comment by ytliang97** [comment]
Yes, it works! Thank you so much! @effigies 

```python
import nibabel as nib
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np

FLAGS = tf.app.flags.FLAGS

tf.app.flags.DEFINE_string(
    'data_path', '',
    'nifti data path.')

#e.g. FLAGS.data_path = 'BraTS19_CBICA_AAB_1_t1ce.nii.gz'

def main(_):
    with open(FLAGS.data_path, 'rb') as f:
        bytes_ = f.read()

        load_from_path = nib.load(FLAGS.data_path)
        load_from_byte = nib.Nifti1Image.from_bytes(bytes_)

        path_data = load_from_path.get_data()
        byte_data = load_from_byte.get_data()
        
        compare = np.array_equal(byte_data, path_data)
        
        print(compare)
        
        print('from path:',path_data.min(), path_data.max())
        print('from byte:', byte_data.min(), byte_data.max())

        plt.subplot(1,2,1)
        plt.imshow(path_data[:,:,50], cmap='Greys_r')
        plt.subplot(1,2,2)
        plt.imshow(byte_data[:,:,50], cmap='Greys_r')
        plt.show()

if __name__ == '__main__':
    tf.app.run()
```

**Comment by ytliang97** [comment]
I just notice that `nib.Nifti1Image.from_bytes()` works for your file is **not compressed**.

that is:

FLAGS.data_path = 'xxx.nii'

not FLAGS.data_path = 'xxx.nii.gz'

so make sure you already uncompress your nifti file.

**Comment by effigies** [comment]
Right. You can separately decompress a byte stream.
