### ISSUE TITLE
Failing tests: Fedora 33 (rawhide): python 3.8

### ISSUE THREAD

**Issue by sanjayankur31** [nipy/nibabel#908]
I was updating the package for Fedora, but I see a lot of tests failing. Not sure if this is a Fedora specific error. I'll test it out in a virtual environment now also, but I thought I'd file an issue:

```
======================================================================
ERROR: nibabel.cmdline.tests.test_conform.test_default
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_default() missing 1 required positional argument: 'tmpdir'

======================================================================
ERROR: nibabel.cmdline.tests.test_conform.test_nondefault
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_nondefault() missing 1 required positional argument: 'tmpdir'

======================================================================
ERROR: nibabel.externals.tests.test_netcdf.test_read_write_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_read_write_files() missing 1 required positional argument: 'tmp_path'

======================================================================
ERROR: nibabel.gifti.tests.test_giftiio.test_read_deprecated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_read_deprecated() missing 1 required positional argument: 'tmp_path'

======================================================================
ERROR: nibabel.tests.test_data.test_data_path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_data_path() missing 1 required positional argument: 'with_nimd_env'

======================================================================
ERROR: nibabel.tests.test_data.test_make_datasource
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_make_datasource() missing 1 required positional argument: 'with_nimd_env'

======================================================================
ERROR: nibabel.tests.test_data.test_bomber
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nibabel-3.1.0/nibabel/tests/test_data.py", line 206, in test_bomber
    b.any_attribute  # no error
  File "/builddir/build/BUILD/nibabel-3.1.0/nibabel/data.py", line 316, in __getattr__
    raise BomberError(
nibabel.data.BomberError: Trying to access attribute "any_attribute" of non-existent data "bomber example"

a message


======================================================================
ERROR: nibabel.tests.test_data.test_datasource_or_bomber
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_datasource_or_bomber() missing 1 required positional argument: 'with_nimd_env'

======================================================================
ERROR: nibabel.tests.test_environment.test_user_dir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_user_dir() missing 1 required positional argument: 'with_environment'

======================================================================
ERROR: nibabel.tests.test_euler.test_euler_mat_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_euler_mat_2() missing 3 required positional arguments: 'x', 'y', and 'z'

======================================================================
ERROR: nibabel.tests.test_euler.test_quats
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_quats() missing 3 required positional arguments: 'x', 'y', and 'z'

======================================================================
ERROR: nibabel.tests.test_init.test_nibabel_test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_nibabel_test() missing 4 required positional arguments: 'verbose', 'v_args', 'doctests', and 'coverage'

======================================================================
ERROR: nibabel.tests.test_pkg_info.test_cmp_pkg_version_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_cmp_pkg_version_1() missing 3 required positional arguments: 'test_ver', 'pkg_ver', and 'exp_out'

======================================================================
ERROR: nibabel.tests.test_pkg_info.test_cmp_pkg_version_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_cmp_pkg_version_error() missing 1 required positional argument: 'args'

======================================================================
ERROR: nibabel.tests.test_quaternions.test_inverse_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_inverse_1() missing 2 required positional arguments: 'M' and 'q'

======================================================================
ERROR: nibabel.tests.test_quaternions.test_mult
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_mult() missing 4 required positional arguments: 'M1', 'q1', 'M2', and 'q2'

======================================================================
ERROR: nibabel.tests.test_quaternions.test_inverse
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_inverse() missing 2 required positional arguments: 'M' and 'q'

======================================================================
ERROR: nibabel.tests.test_quaternions.test_qrotate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_qrotate() missing 3 required positional arguments: 'vec', 'M', and 'q'

======================================================================
ERROR: nibabel.tests.test_quaternions.test_quaternion_reconstruction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_quaternion_reconstruction() missing 1 required positional argument: 'q'

======================================================================
ERROR: nibabel.tests.test_scaling.test_finite_range
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_finite_range() missing 2 required positional arguments: 'in_arr' and 'res'

======================================================================
ERROR: nibabel.tests.test_scaling.test_a2f_mn_mx
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_a2f_mn_mx() missing 1 required positional argument: 'out_type'

======================================================================
ERROR: nibabel.tests.test_scaling.test_array_file_scales
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_array_file_scales() missing 2 required positional arguments: 'in_type' and 'out_type'

======================================================================
ERROR: nibabel.tests.test_scaling.test_scaling_in_abstract
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_scaling_in_abstract() missing 3 required positional arguments: 'category0', 'category1', and 'overflow'

======================================================================
ERROR: nibabel.tests.test_scripts.test_nib_ls
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_nib_ls() missing 1 required positional argument: 'args'

======================================================================
ERROR: nibabel.tests.test_spaces.test_slice2volume_exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_slice2volume_exception() missing 2 required positional arguments: 'index' and 'axis'

======================================================================
ERROR: nibabel.tests.test_testing.test_assert_re_in
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_assert_re_in() missing 2 required positional arguments: 'regex' and 'entries'

----------------------------------------------------------------------
Ran 2058 tests in 122.871s

```

Downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1811945

**Comment by sanjayankur31** [comment]
Here is an example (failing) scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=43988067

logs attached:

- [buildlog.txt](https://github.com/nipy/nibabel/files/4565619/buildlog.txt)
- [rootlog.txt](https://github.com/nipy/nibabel/files/4565628/rootlog.txt)

**Comment by effigies** [comment]
It looks like you're still using nose. We've switched to pytest. Does that work?

**Comment by sanjayankur31** [comment]
> It looks like you're still using nose. We've switched to pytest. Does that work?

Ah, yes, pytest seems to work:

```
===== 4661 passed, 109 skipped, 6 xfailed, 5638 warnings in 133.47 seconds =====
```

Thanks! I'll go push the update now! :)
