### ISSUE TITLE
AttributeError raised in OrthoSlicer3D

### ISSUE THREAD

**Issue by fepegar** [nipy/nibabel#920]
I'm trying to visualize a volume using `OrthoSlicer3D`, but get a `matplotlib` error:

Script:

```python
import numpy as np
from nibabel.viewers import OrthoSlicer3D as ov
data = np.ones((5, 5, 5))
ov(data)
```

Output:

```python-traceback
Traceback (most recent call last):
  File "ov.py", line 4, in <module>
    ov(data)
  File "/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/nibabel/viewers.py", line 213, in __init__
    self._draw()
  File "/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/nibabel/viewers.py", line 503, in _draw
    ax.draw_artist(self._ims[ii])
  File "/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2642, in draw_artist
    raise AttributeError("draw_artist can only be used after an "
AttributeError: draw_artist can only be used after an initial draw which caches the renderer
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/torchio/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 196, in process
    func(*args, **kwargs)
TypeError: _cleanup() takes 1 positional argument but 2 were given
```

**Comment by effigies** [comment]
Guessing this is with a recent matplotlib release? They may have made the method keyword only.

**Comment by fepegar** [comment]
Yes, latest `matplotlib` and `nibabel`.

Oh, looks like @matthew-brett has chased this before: https://discourse.matplotlib.org/t/confusion-about-draw-artist/19891

I'm indeed using macOS.

**Comment by fepegar** [comment]
I've also found this mysterious warning: https://render.githubusercontent.com/view/ipynb?commit=09cdc5ebe1ffe31608756e79c6cb1848742e6969&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6e6970792f776f726b73686f70732f303963646335656265316666653331363038373536653739633663623138343837343265363936392f3137303332372d6e69707970652f6e6f7465626f6f6b732f6e69626162656c5f6e696c6561726e2f6e69626162656c5f6e696c6561726e2e6970796e62&nwo=nipy%2Fworkshops&path=170327-nipype%2Fnotebooks%2Fnibabel_nilearn%2Fnibabel_nilearn.ipynb&repository_id=5728333&repository_type=Repository#Warning

**Comment by effigies** [comment]
I think this is a duplicate of #433, then. Sorry about the delay, but can you follow-up there, if you learn anything?

**Comment by effigies** [comment]
Well, I'll leave it to you to decide if this is a duplicate... Please close if so. :-)

**Comment by fepegar** [comment]
I would say it's not, although they might be related. I'll keep you posted.

**Comment by 0xSMT** [comment]
Any follow ups on this? I recently ran into the same problem.

**Comment by chaoers** [comment]
I'm using OSX 11.3.1 and I have got the same error. After I set matplotlib backend to `TkAgg`, it seems work right.

```python
import nibabel as nib
from nibabel.viewers import OrthoSlicer3D
import matplotlib
matplotlib.use('TkAgg') # 注意这行要在 import plt之前 It should before import plt
from matplotlib import pylab as plt
```

**Comment by fepegar** [comment]
Using the `TkAgg` backend, the viewer is shown, but
1. The slices are black
2. I can't close the figure
3. I still get a `TypeError`

**Comment by fepegar** [comment]
I can see the image using `img.orthoview()` as suggested by @effigies in #433 (and `TkAgg`), but I get issues 2 and 3 of my previous comment.

**Comment by chaoers** [comment]
> Using the `TkAgg` backend, the viewer is shown, but
> 
> 1. The slices are black
> 2. I can't close the figure
> 3. I still get a `TypeError`

You should click the first window to change view location（it's normal black if the location is (0,0)）.

And if the Python program is down（ctrl + Z）, the fighre will close.

**Comment by fepegar** [comment]
> You should click the first window to change view location（it's normal black if the location is (0,0)）.

You're right, thanks!

> And if the Python program is down（ctrl + Z）, the figure will close.

This didn't work for me, but pressing `q` did.
