### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by tanjia123456** [nipy/nibabel#962]
hello, I'm sorry to bother you again
when I use the following code to read and wtite annotation file:
`import warnings
import numpy as np
import getpass
import time

from collections import OrderedDict
#from ..openers import Opener

_ANNOT_DT = ">i4"

def read_annot(filepath, orig_ids=False):
    """从.annot文件中加入Freesurfer注释。.annot文件包含带有标签的一系列顶点（也称为
     作为与每个顶点相关联的“注释值”），然后是一个序列每个标签对应的颜色。支持注释文件格式版本1和2，分别对应
     “旧样式”和“新样式”颜色表布局。请注意，输出颜色表``ctab''是RGBT形式，其中T（透明度）为255-alpha。
    See:
     * https://surfer.nmr.mgh.harvard.edu/fswiki/LabelsClutsAnnotationFiles#Annotation
     * https://github.com/freesurfer/freesurfer/blob/dev/matlab/read_annotation.m
     * https://github.com/freesurfer/freesurfer/blob/8b88b34/utils/colortab.c
    Parameters
    ----------
    filepath : str    Path to annotation file.
    orig_ids : bool   是否返回存储在注释中的顶点ID文件或位置颜色表ID。 使用orig_ids = False  没有id的顶点的id设置为-1。
    Returns
    -------
    labels : ndarray, shape (10242,) 每个顶点处的注释ID。 如果一个顶点不属于到任何标签且orig_ids = False，其id将设置为-1。
    ctab : ndarray, shape (n_labels, 5)   RGBT + label id colortable array.
    names : list of bytes   The names of the labels. The length of the list is n_labels.
    """
    with open(filepath, "rb") as fobj:
        dt = _ANNOT_DT

        # number of vertices
        vnum = np.fromfile(fobj, dt, 1)[0]

        # vertex ids + annotation values
        data = np.fromfile(fobj, dt, vnum * 2).reshape(vnum, 2)
        #data = np.fromfile(list(fobj, dt, vnum * 2)).reshape(vnum, 2)
        labels = data[:, 1]

        # is there a color table?
        ctab_exists = np.fromfile(fobj, dt, 1)[0]
        if not ctab_exists:
            raise Exception('Color table not found in annotation file')

        n_entries = np.fromfile(fobj, dt, 1)[0]

        # We've got an old-format .annot file.
        if n_entries > 0:
            ctab, names = _read_annot_ctab_old_format(fobj, n_entries)
        # We've got a new-format .annot file
        else:
            ctab, names = _read_annot_ctab_new_format(fobj, -n_entries)

    # generate annotation values for each LUT entry
    ctab[:, [4]] = _pack_rgb(ctab[:, :3])

    if not orig_ids:
        ord = np.argsort(ctab[:, -1])
        mask = labels != 0
        labels[~mask] = -1
        labels[mask] = ord[np.searchsorted(ctab[ord, -1], labels[mask])]
    return labels, ctab, names

def _read_annot_ctab_old_format(fobj, n_entries):
    """Note that the output color table ``ctab`` is in RGBT form, where T(transparency) is 255 - alpha.
    This function is used by :func:`read_annot`.
    Parameters
    ----------
    fobj : file-like
        Open file handle to a Freesurfer `.annot` file, with seek point
        at the beginning of the color table data.
    n_entries : int   Number of entries in the color table.
    Returns
    -------
    ctab : ndarray, shape (n_entries, 5)
        RGBT colortable array - the last column contains all zeros.
    names : list of str
        The names of the labels. The length of the list is n_entries.
    """
    assert hasattr(fobj, 'read')

    dt = _ANNOT_DT
    # orig_tab string length + string
    length = np.fromfile(fobj, dt, 1)[0]
    orig_tab = np.fromfile(fobj, '>c', length)
    orig_tab = orig_tab[:-1]
    names = list()
    ctab = np.zeros((n_entries, 5), dt)
    for i in range(n_entries):
        # structure name length + string
        name_length = np.fromfile(fobj, dt, 1)[0]
        name = np.fromfile(fobj, "|S%d" % name_length, 1)[0]
        names.append(name)
        # read RGBT for this entry
        ctab[i, :4] = np.fromfile(fobj, dt, 4)

    return ctab, names

def _read_annot_ctab_new_format(fobj, ctab_version):
    """Read in a new-style Freesurfer color table from `fobj`.Note that the output color table ``ctab`` is in RGBT form, where T
    (transparency) is 255 - alpha.
    This function is used by :func:`read_annot`.
    Parameters
    ----------
    fobj : file-like
        Open file handle to a Freesurfer `.annot` file, with seek point
        at the beginning of the color table data.
    ctab_version : int
        Color table format version - must be equal to 2
    Returns
    -------
    ctab : ndarray, shape (n_labels, 5)
        RGBT colortable array - the last column contains all zeros.
    names : list of str
        The names of the labels. The length of the list is n_labels.
    """
    assert hasattr(fobj, 'read')

    dt = _ANNOT_DT
    # This code works with a file version == 2, nothing else
    if ctab_version != 2:
        raise Exception('Unrecognised .annot file version (%i)', ctab_version)
    # maximum LUT index present in the file
    max_index = np.fromfile(fobj, dt, 1)[0]
    ctab = np.zeros((max_index, 5), dt)
    # orig_tab string length + string
    length = np.fromfile(fobj, dt, 1)[0]
    np.fromfile(fobj, "|S%d" % length, 1)[0]  # Orig table path
    # number of LUT entries present in the file
    entries_to_read = np.fromfile(fobj, dt, 1)[0]
    names = list()
    for _ in range(entries_to_read):
        # index of this entry
        idx = np.fromfile(fobj, dt, 1)[0]
        # structure name length + string
        name_length = np.fromfile(fobj, dt, 1)[0]
        name = np.fromfile(fobj, "|S%d" % name_length, 1)[0]
        names.append(name)
        # RGBT
        ctab[idx, :4] = np.fromfile(fobj, dt, 4)

    return ctab, names

def _pack_rgb(rgb):
    bitshifts = 2 ** np.array([[0], [8], [16]], dtype=rgb.dtype)
    return rgb.dot(bitshifts)

def write_annot(filepath, labels, ctab, names, fill_ctab=True):
    """Write out a "new-style" Freesurfer annotation file.
    Note that the color table ``ctab`` is in RGBT form, where T (transparency)
    is 255 - alpha.
    Parameters
    ----------
    filepath : str
        Path to annotation file to be written
    labels : ndarray, shape (n_vertices,)
        Annotation id at each vertex.
    ctab : ndarray, shape (n_labels, 5)
        RGBT + label id colortable array.
    names : list of str
        The names of the labels. The length of the list is n_labels.
    fill_ctab : {True, False} optional
        If True, the annotation values for each vertex  are automatically
        generated. In this case, the provided `ctab` may have shape
        (n_labels, 4) or (n_labels, 5) - if the latter, the final column is
        ignored.
    """
    with open(filepath, "wb") as fobj:
        dt = _ANNOT_DT
        vnum = len(labels)

        def write(num, dtype=dt):
            np.array([num]).astype(dtype).tofile(fobj)

        def write_string(s):
            s = (s if isinstance(s, bytes) else s.encode()) + b'\x00'
            write(len(s))
            write(s, dtype='|S%d' % len(s))

        # Generate annotation values for each ctab entry
        if fill_ctab:
            ctab = np.hstack((ctab[:, :4], _pack_rgb(ctab[:, :3])))
        elif not np.array_equal(ctab[:, [4]], _pack_rgb(ctab[:, :3])):
            warnings.warn(f'Annotation values in {filepath} will be incorrect')

        # vtxct
        write(vnum)

        # convert labels into coded CLUT values
        clut_labels = ctab[:, -1][labels]
        clut_labels[np.where(labels == -1)] = 0

        # vno, label
        data = np.vstack((np.array(range(vnum)),
                          clut_labels)).T.astype(dt)
        data.tofile(fobj)

        # tag
        write(1)

        # ctabversion
        write(-2)

        # maxstruc
        write(max(np.max(labels) + 1, ctab.shape[0]))

        # File of LUT is unknown.
        write_string('NOFILE')

        # num_entries
        write(ctab.shape[0])

        for ind, (clu, name) in enumerate(zip(ctab, names)):
            write(ind)
            write_string(name)
            for val in clu[:-1]:
                write(val)

#加载更新后的label值，并且要将最后一个空白行删掉才行
updated_data=np.loadtxt('labels_target_1.txt')#用作索引的数组必须是整数（或布尔）类型,按照下面进行类型转换即可
updated_data.astype('int64')
read_annotation=read_annot('rh.aparc.a2009s.annot', orig_ids=False)
'''labels : ndarray, shape (10242,) 每个顶点处的注释ID。 如果一个顶点不属于到任何标签且orig_ids = False，其id将设置为-1。
    ctab : ndarray, shape (n_labels, 5)   RGBT + label id colortable array.
    names '''
print('labels:',read_annotation[0])
print('ctab:',read_annotation[1])
print('names:',read_annotation[2])
'''write_annot(filepath, labels, ctab, names, fill_ctab=True):'''
write_annotation=write_annot('rh.aparc.a2009s.annot', updated_data, read_annotation[1],read_annotation[2], fill_ctab=True)`

the error occurs:
Traceback (most recent call last):
  File "C:/Users/hp/Desktop/full_supervised/annotation_visual1/read_nibeal_annot.py", line 234, in <module>
    write_annotation=write_annot('rh.aparc.a2009s.annot', updated_data, read_annotation[1],read_annotation[2], fill_ctab=True)
  File "C:/Users/hp/Desktop/full_supervised/annotation_visual1/read_nibeal_annot.py", line 194, in write_annot
    clut_labels = ctab[:, -1][labels]
IndexError: arrays used as indices must be of integer (or boolean) type

do you know how to solve it?

**Comment by tanjia123456** [comment]
Running it again will cause the following error

Traceback (most recent call last):
  File "C:/Users/hp/Desktop/full_supervised/annotation_visual1/read_nibeal_annot1.py", line 229, in <module>
    read_annotation=read_annot('rh.aparc.a2009s.annot', orig_ids=False)
  File "C:/Users/hp/Desktop/full_supervised/annotation_visual1/read_nibeal_annot1.py", line 42, in read_annot
    data = np.fromfile(fobj, dt, vnum * 2).reshape(vnum, 2)
ValueError: cannot reshape array of size 0 into shape (10242,2)
