### ISSUE TITLE
`Too many open files`: Cannot close a file

### ISSUE THREAD

**Issue by TomMaullin** [nipy/nibabel#981]
I have written the below function which I use to:

 1. Check if a Nifti exists named `fname`. If it does exist the function reads it into memory and if not it initializes the file `fname` as an array of zeros with dimension `dim`, affine `aff` and header `hdr`. 
 2. It then replaces the voxels in the image which have indices `blockInds` (in flattened/1d form) with the values stored in `block` and saves the result.

Sometimes I am interested in one particular volume in a 4D nifti image. In this case, I use the `volInd` argument to specify which 3D volume inside a 4D nifti file I wish to edit.

```
def addBlockToNifti(fname, block, blockInds,dim=None,volInd=None,aff=None,hdr=None):

    # Check if file is in use
    fileLocked = True
    while fileLocked:
        try:
            # Create lock file, so other jobs know we are writing to this file
            os.open(fname + ".lock", os.O_CREAT|os.O_EXCL|os.O_RDWR)
            fileLocked = False
        except FileExistsError:
            fileLocked = True

    # Check volInd is correct datatype
    if volInd is not None:

        volInd = int(volInd)

    print(fname)
    print(os.path.isfile(fname))

    # Check whether the NIFTI exists already
    if os.path.isfile(fname):

        print('here')

        # Load in NIFTI
        img = nib.Nifti1Image.from_filename(fname, mmap=False)

        # Work out dim if we don't already have it
        dim = img.shape

        print('in mem 1 ', img.in_memory)

        # Work out data
        data = img.get_fdata().copy()
        # data_array = np.asarray(img.dataobj)

        print('in mem 2 ', img.in_memory)

        # Work out affine
        affine = img.affine.copy()

        # Delete image
        img.uncache()

        print('in mem 3 ', img.in_memory)
        del img
        
    else:

        print('here2')

        # If we know how, make the NIFTI
        if dim is not None:
            
            # Make data
            data = np.zeros(dim)

            # Make affine
            if aff is None:
                affine = np.eye(4)
            else:
                affine = aff

        else:

            # Throw an error because we don't know what to do
            raise Exception('NIFTI does not exist and dimensions not given')

    # Work out the number of output volumes inside the nifti 
    if len(dim)==3:

        # We only have one volume in this case
        n_vol = 1
        dim = np.array([dim[0],dim[1],dim[2],1])

    else:

        # The number of volumes is the last dimension
        n_vol = dim[3]

    # Seperate copy of data for outputting
    data_out = np.array(data).reshape(dim)

    # Work out the number of voxels
    n_vox = np.prod(dim[:3])

    # Reshape     
    data = data.reshape([n_vox, n_vol])

    # Add all the volumes
    if volInd is None:

        # Add block
        data[blockInds,:] = block.reshape(data[blockInds,:].shape)
        
        # Cycle through volumes, reshaping.
        for k in range(0,data.shape[1]):

            data_out[:,:,:,k] = data[:,k].reshape(int(dim[0]),
                                                  int(dim[1]),
                                                  int(dim[2]))

    # Add the one volume in the correct place
    else:

        # We're only looking at this volume
        data = data[:,volInd].reshape((n_vox,1))

        # Add block
        data[blockInds,:] = block.reshape(data[blockInds,:].shape)
        
        # Put in the volume
        data_out[:,:,:,volInd] = data[:,0].reshape(int(dim[0]),
                                                 int(dim[1]),
                                                 int(dim[2]))


    # Make NIFTI
    nifti = nib.Nifti1Image(data_out, affine, header=hdr)
    
    print('in mem 4 ', nifti.in_memory)
    
    # Save NIFTI
    nib.save(nifti, fname)

    # Uncache NIFTI
    nifti.uncache()

    print('in mem 5 ', nifti.in_memory)

    # Delete lock file, so other jobs know they can now write to the
    # file
    os.remove(fname + ".lock")

    del nifti, fname, data_out, affine
```

I use this function to add groups of voxels to an image incrementally when I am generating test data that cannot be generated for all voxels at once. The reason I can't do all voxels at once is due to between-nifti covariance structures I need to model in my data.

As a result, I end up calling my function above a lot (approximately 250 times in the scenario I am currently working on). But, currently, it is not working as it appears some of the files I create are not closing.

The error I am getting is the below:

```
Traceback (most recent call last):
  File "/home/tommaullin/Documents/BLMM/sim/generateData.py", line 492, in addBlockToNifti
  File "/home/tommaullin/.local/lib/python3.6/site-packages/nibabel/keywordonly.py", line 17, in wrapper
  File "/home/tommaullin/.local/lib/python3.6/site-packages/nibabel/dataobj_images.py", line 492, in from_filename
  File "/home/tommaullin/.local/lib/python3.6/site-packages/nibabel/keywordonly.py", line 17, in wrapper
  File "/home/tommaullin/.local/lib/python3.6/site-packages/nibabel/analyze.py", line 974, in from_file_map
  File "/home/tommaullin/.local/lib/python3.6/site-packages/nibabel/fileholders.py", line 70, in get_prepare_fileobj
  File "/home/tommaullin/.local/lib/python3.6/site-packages/nibabel/openers.py", line 111, in __init__
OSError: [Errno 24] Too many open files: '/home/tommaullin/Documents/BLMM/sim/data/b17.nii'
```

I believe my problem might be coming fro the variable `nifti`, which does not seem to want to uncache (see the `in mem 5 ` print statement). 

Have I misunderstood something here? I have tried everything I can think of but I can't seem to get the files I open in `addBlockToNifti` to close.

**Comment by effigies** [comment]
Looking at this, I'd guess that your problem is `os.open(fname + ".lock", os.O_CREAT|os.O_EXCL|os.O_RDWR)`, which opens a file and never closes it.

I might consider using a file locking library like [filelock](https://pypi.org/project/filelock/) to take advantage of somebody else already thinking through the problem.

**Comment by TomMaullin** [comment]
Perhaps this could be the cause... I believe the filelock code I used was adapted from the [FileLock package](https://github.com/dmfrey/FileLock) though. I am still unsure how can I uncache the `nifti` file in the above code?

**Comment by effigies** [comment]
It seems pretty thoroughly uncached. But logically, if you're able to open a nifti file, then you'll be able to open the next lock file. So you'll hit your open file limit on a nifti file.

**Comment by TomMaullin** [comment]
Yes that makes sense - thank you!
